# coding: utf-8  

message (STATUS "	BUILD_STATIC		${BUILD_STATIC}")
message (STATUS "	BUILD_TOOLS		${BUILD_TOOLS}")
message (STATUS "	ENDIANNESS		${WORDS_BIGENDIAN} (0=Little, 1=Big)")
message (STATUS "	TYPE64			${TYPE64}")
message (STATUS "	TYPEU64			${TYPEU64}")
message (STATUS "	UTF8CPP_INTERNAL	${UTF8CPP_INTERNAL}")
