# coding: utf-8

SET(PO4A_TRANSLATE_PERCENT 0)
SET(PO4A_FLAGS -M utf-8 -k ${PO4A_TRANSLATE_PERCENT})
SET(PO4A_TRANSLATE_FLAGS ${PO4A_FLAGS} -f docbook)
find_program(PO4A "po4a")
find_program(PO4A_TRANSLATE "po4a-translate")

SET(PO4A_WORKS OFF)
IF (PO4A AND PO4A_TRANSLATE)
	SET(FILE_ARG_1 -m ${CMAKE_SOURCE_DIR}/doc/man/mkvmerge.xml)
	SET(FILE_ARG_2 -p ${CMAKE_SOURCE_DIR}/doc/man/po4a/po/ja.po)
	SET(FILE_ARG_3 -l /dev/null)
	execute_process(COMMAND ${PO4A_TRANSLATE} ${PO4A_TRANSLATE_FLAGS}
		${FILE_ARG_1} ${FILE_ARG_2} ${FILE_ARG_3}
		RESULT_VARIABLE PO4A_WORKS_RESULT
	)
	
	IF (${PO4A_WORKS_RESULT} MATCHES "0")
		SET(PO4A_WORKS ON)
	ENDIF (${PO4A_WORKS_RESULT} MATCHES "0")
ENDIF (PO4A AND PO4A_TRANSLATE)
